/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/51dDab3eSoL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardContent, CardFooter } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Chatbot() {
  return (
    <Card className="w-full max-w-md mx-auto">
      <CardHeader className="flex flex-row items-center">
        <div className="flex items-center space-x-4">
          <Avatar>
            <AvatarImage src="/placeholder-user.jpg" alt="DOJ Chatbot" />
            <AvatarFallback>DOJ</AvatarFallback>
          </Avatar>
          <div>
            <p className="text-sm font-medium leading-none">Department of Justice Chatbot</p>
            <p className="text-sm text-muted-foreground">How can I assist you today?</p>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm bg-muted">
            Hello, I'm the Department of Justice chatbot. How can I help you today?
          </div>
          <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm bg-muted">
            I can provide information about the DOJ's services, policies, and procedures. Please let me know what you'd
            like to know more about.
          </div>
          <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm bg-primary text-primary-foreground">
            I'm interested in learning more about the DOJ's criminal justice reform initiatives. Can you tell me about
            some of the key programs and policies in this area?
          </div>
          <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm bg-muted">
            Certainly. The DOJ has several initiatives aimed at reforming the criminal justice system, including:
            <ul className="list-disc pl-4 mt-2">
              <li>The First Step Act, which focuses on sentencing reform and prisoner reentry programs</li>
              <li>
                The Smart on Crime initiative, which emphasizes prevention, rehabilitation, and alternatives to
                incarceration
              </li>
              <li>
                The National Initiative for Building Community Trust and Justice, which works to improve
                police-community relations
              </li>
            </ul>
            Let me know if you have any other questions about these programs.
          </div>
          <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm bg-primary text-primary-foreground">
            That's very helpful, thank you. I also had a question about the DOJ's role in civil rights enforcement. Can
            you tell me more about that?
          </div>
          <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm bg-muted">
            The DOJ plays a critical role in enforcing federal civil rights laws. Some of the key areas the DOJ focuses
            on include:
            <ul className="list-disc pl-4 mt-2">
              <li>
                Protecting the rights of vulnerable populations, such as racial minorities, women, and the disabled
              </li>
              <li>Investigating and prosecuting hate crimes and other civil rights violations</li>
              <li>Ensuring equal access to housing, education, employment, and other public services</li>
            </ul>
            The DOJ's Civil Rights Division leads many of these efforts. Let me know if you need any clarification or
            have additional questions.
          </div>
          <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm bg-primary text-primary-foreground">
            That's very informative, thank you. I think I have a good understanding now, but if I have any other
            questions, can I come back and chat with you again?
          </div>
          <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm bg-muted">
            Absolutely, I'm always here to help. Feel free to come back anytime you have additional questions or need
            further assistance. I'm happy to provide more information or escalate your query to a human representative
            if needed.
          </div>
        </div>
      </CardContent>
      <CardFooter>
        <form className="flex items-center w-full space-x-2">
          <Input id="message" placeholder="Type your question..." className="flex-1" autoComplete="off" />
          <Button type="submit" size="icon">
            <SendIcon className="w-4 h-4" />
            <span className="sr-only">Send</span>
          </Button>
        </form>
      </CardFooter>
    </Card>
  )
}

function SendIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}
